[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["build"]

[tasks.check]
description = "Check client"
command = "cargo"
args = ["check", "--lib", "--target", "wasm32-unknown-unknown"]

[tasks.build]
description = "Build client"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]
