[package]
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
default-run = "server"
edition = "2018"
name = "binance-bot"
version = "0.1.0"
[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
lazy_static = "^1.4"
serde_json = "^1"
tracing = "^0.1"
tracing-subscriber = "^0.2"

[dependencies.chrono]
features = ["serde"]
version = "^0.4"

[dependencies.futures]
version = "0.3"

[dependencies.futures-core]
version = "^0.3"

[dependencies.openlimits]
path = "../openlimits"

[dependencies.app-model]
path = "../app-model"

[dependencies.serde]
version = "^1"
features = [
  "derive",
]

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "^1"
async-h1 = "^2"
clap = "^2"
regex = "^1.3"
telegram-bot = "^0.7"
tracing-appender = "^0.1"
parallel-stream = "^2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.warp]
version = "^0.2"
features = [
  "tls",
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "^0.2"
features = [
  "fs",
  "rt-threaded",
  "tcp",
  "stream",
  "macros",
]
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio-util]
version = "^0.3"
features = [
  "compat",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "^0.1"
rand = "^0.7"
rand_distr = "^0.2"
rust_decimal = "^1"
url = "^2"
wasm-bindgen-futures = "^0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies.enum_paths]
path = "../enum_paths"

[target.'cfg(target_arch = "wasm32")'.dependencies.tracing-wasm]
path = "../tracing-wasm"

[target.'cfg(target_arch = "wasm32")'.dependencies.components]
path = "../components"

[target.'cfg(target_arch = "wasm32")'.dependencies.js-sys]
version = "^0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies.seed]
branch = "master"
git = "https://github.com/seed-rs/seed"

[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "^0.2"
features = [
  "serde-serialize"
]

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "^0.3"
features = [
  "MutationObserver",
  "MutationRecord",
  "Node",
  "Document",
  "Window",
]
