[env]
PORT = "8000"

[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["start"]

[tasks.start]
description = "Start server"
command = "cargo"
args = ["run"]
dependencies = ["client"]

[tasks.client]
description = "Build client"
command = "cargo"
args = ["make", "--cwd", "./client"]

